### ISSUE TITLE
AI Plays Guff Rewrites History Incorrectly

### ISSUE THREAD

**Issue by ItsGoldeneyes** [Card-Forge/forge#4957] opened 2024-04-04 22:22 UTC
**Describe the bug**
Guff Rewrites History involves choosing one permanent from each player, shuffling them in, then exiling from each player's deck until they hit a permanent. Instead of choosing one permanent from each player, AI chooses multiple from one player.

**To Reproduce**
1. 4 Player game with 2 players with at least 1 permanent, AI with Guff Rewrites History and 1 player with many permanents
2. AI cast Guff Rewrites History
3. AI selects 4 permanents from one player
4. Results in only one permanent getting shuffled

**Expected behavior**
AI should choose one permanent from each player, not 4 from one.

**Screenshots**
AI's chosen targets
![AI's chosen targets](https://github.com/Card-Forge/forge/assets/97778776/06752810-2b7e-40d6-b9e3-1987ecbf2a60)

Targeted board
![Targeted board](https://github.com/Card-Forge/forge/assets/97778776/c47c40d1-f9ef-4d5d-bf72-aae26f17d672)

Other player's boards
![Other players boards](https://github.com/Card-Forge/forge/assets/97778776/95208dfc-250c-4d77-96c6-46611993cd17)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by tool4ever** [comment] 2024-04-05 05:14
Duplicate of #4242

**Closed by tool4ever** 2024-04-05 05:14 UTC
