### ISSUE TITLE
AI in multiplayer games is not bound by "once per player" targeting restrictions

### ISSUE THREAD

**Issue by Ampersandnz** [Card-Forge/forge#5002] opened 2024-04-10 22:19 UTC
I believe I've also seen this happen with cards like [Shadrix Silverquill](https://scryfall.com/card/stx/230/shadrix-silverquill)

![image](https://github.com/Card-Forge/forge/assets/3029794/e645e5ae-26eb-4f5b-b54d-7901a2f1bf9b)

Version is commit d154655 from a week ago, PC client

**Comment by tool4ever** [comment] 2024-04-11 05:59
Duplicate of #4242

**Closed by tool4ever** 2024-04-11 05:59 UTC
