### ISSUE TITLE
Game keeps freezing on "Waiting for Opponent"

### ISSUE THREAD

**Issue by Nymra** [Card-Forge/forge#6198] opened 2024-09-26 05:49 UTC
I noticed this happens more likely when an AI in a 4P game (3 AIs, one Human) is defeated.

Log attaced

[forge.log](https://github.com/user-attachments/files/17143380/forge.log)

**Comment by tool4ever** [comment] 2024-09-26 05:55
Duplicate of #4399

**Closed by tool4ever** 2024-09-26 05:55 UTC
