### ISSUE TITLE
AI ignoring for each opponent targeting restriction

### ISSUE THREAD

**Issue by petersul** [Card-Forge/forge#6375] opened 2024-10-17 13:18 UTC
**Describe the bug**
When the AI plays Hatham Kenway it is able to use his triggered ability to target multiple creatures with the same controller when it should be limited to one creature for each player. The targeting restrictions apply correctly when the user is choosing the targets but appear to be ignored when the AI is choosing targets.

**To Reproduce**
1. Create a deck with just Haytham and lands
2. Start a game with multiple AI opponents which are all using the deck
3. Play multiple creatures
4. When one of the AI play Haytham it will incorrectly target multiple creatures with the same controller

**Expected behavior**
Haytham's ability should only be able to target up to one creature controlled by each opponent

**Screenshots**
![image](https://github.com/user-attachments/assets/ccfe3674-271d-4d56-bb69-ea6d2ce64bb8)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 1.6.66-SNAPSHOT-10-16

**Comment by tool4ever** [comment] 2024-10-17 13:29
Duplicate of #4242

**Closed by tool4ever** 2024-10-17 13:29 UTC
