### ISSUE TITLE
Brainstorm orders cards on top of library incorrectly

### ISSUE THREAD

**Issue by Goddfrey** [Card-Forge/forge#6161] opened 2024-09-17 03:03 UTC
When you get the ordering window with "Closest to top", it's the bottom card on the list that's gonna be on top of the library. Weirdly the issue is specific to Brainstorm, i.e. Ponder orders them correctly.

 - OS: Windows 10
 - Version 1.6.64

**Comment by tool4ever** [comment] 2024-09-17 05:23
Duplicate of #5466

**Closed by tool4ever** 2024-09-17 05:23 UTC
