### ISSUE TITLE
Game still unplayable vs AI in EDH

### ISSUE THREAD

**Issue by Nymra** [Card-Forge/forge#5747] opened 2024-07-31 23:05 UTC
Ever since the experimental go back feature was introduced, the game is basically disfunct.
I can only finish every other game, if I am lucky and do the right steps to prevent bugs.

- Commander cost still rises too fast. still could not reproduce this reliably, sorry. it just happens 
- game freezes when I press "cancel"
- game freezes when I cant pay the mana of a spell
- game freezes on opponents "thinking" 

I basically have to prevent all the above from happening and still 50% of games bug out.
I cannot even LOOK at the current command tax of my commander without risking the value to increase.

Please, this is really depressing, I played forge for hours, now its basically once a week to test a new version, but all the bugs are persistent. 

Its funny that even my old bug threads are ignored...

**Comment by tehdiplomat** [comment] 2024-07-31 23:14
Got any log files? I was finally able to reproduce the commander cost bug recently and fixed it.

**Comment by Nymra** [comment] 2024-07-31 23:23
> Got any log files? I was finally able to reproduce the commander cost bug recently and fixed it.

is it fixed in the latest version? not sure if this is the correct version info (from Release notes) forge-1.6.63

Have not worked with Log Files yet, where are they stored? do I have to enable something for them to be created?

**Comment by tehdiplomat** [comment] 2024-07-31 23:32
Thats the most recent release, but its 2 months old. It's fixed in the snapshots.

**Comment by tool4ever** [comment] 2024-08-28 19:52
Closing as duplicate of #5467

**Closed by tool4ever** 2024-08-28 19:52 UTC
