### ISSUE TITLE
Retrieve should return both targets simultaneously

### ISSUE THREAD

**Issue by Northmoc** [Card-Forge/forge#4962] opened 2024-04-05 12:56 UTC
Also an issue for:
 - Aether Tradewinds
 - Churning Eddy
 - Crop Sigil
 - probably more

> @tool4ever @Northmoc we probably need to reutrn the cards at the same time?

_Originally posted by @Hanmac in https://github.com/Card-Forge/forge/pull/4947#discussion_r1552051980_

**Comment by tool4ever** [comment] 2024-04-05 13:01
imo closeable as duplicate of #1182 :P

**Closed** 2024-04-05 13:01 UTC
Labels: Card Cleanup, Rules compliance
