### ISSUE TITLE
[Suggestion] Proper support for "create a token of specific card" (comp rule 111.11)

### ISSUE THREAD

**Issue by Lykrast** [Card-Forge/forge#5978] opened 2024-08-23 22:39 UTC
**Is your feature request related to a problem? Please describe.**
Using rule 111.11 there are cards that make token copies of defined cards. As of now, in the legacy card pool it's only Disa the Restless, Tarmogoyf Nest, and Ral and the Implicit Maze. (this is different from casting copies like Garth One-Eye, and I'm not talking about that here)

How they work right now is that there's just a token script for the cards they make, instead of having a proper system to create a token of any named card. It's currently fine because there's only 2 tokens on 3 cards, but there's a few issues:

* It's annoying to make a new card that uses it, because you gotta duplicate the card script for the token.
* It's extra work to remember to update the copied token scripts, if for some reason Tarmogoyf or Spellgorger Weird get erratas later down the line (like with Foundations coming out).

I don't expect there to be many more cards like them in the future in the legacy card pool, so it's not a pressing issue. But for the "playtest" card pool there's a bunch of them already, like notably Who's That Praetor?, which is in Mystery Booster 2.

**Describe the solution you'd like**
Some parameter for the Token thing to specify "don't look for a token script, but look for a permanent card with that name", like Garth One-Eye can. Or the card script name maybe? Dunno what would be better.

Would also need to use the token art if available (mh3 has token art for Tarmogoyf and Spellgorger Weird), and maybe if that fails fall back to the actual card art.

I dunno enough about the codebase to pr that :(

**Additional context**
Rule 111.11 in question:
> If an effect instructs a player to create a token by name, doesn’t define any other characteristics
for that token, and the name is not one of the types in the list of predefined tokens above, that player
uses the card with that name in the Oracle card reference to determine the characteristics of that
token.

List of non-legacy card this would affect/help make:
Mystery Booster 1:
* Domesticated Mammoth
* Waste Land (maybe? the text is vague)

Mystery Booster 2:
* Map to Lorthos's Temple
* Who's That Praetor?

Unknown Events:
* Call Up Emrakul to Help
* Kylem All-Star
* Form of the Stax Player
* Slobad, Actually Just Fine (though not sure that card is currently doable)
* Rankle, Master of Pranksters
* Princess Snowfall
* Investi-Gate
* The Crab Queen
* ~~The Disciple of Vess~~ (nvm that one would require naming at random from the card pool, which sounds like a separate thing that I don't think any other card will need besides The Disciple of Nissa (which is also an unknown event card))
* The Dogronmaster
* The Scholar of Seas
* The Ash Lizard
* The Joiner of Cats
* The Wise Sable

**Comment by Hanmac** [comment] 2024-08-24 15:04
Duplicate of #5416

**Comment by Lykrast** [comment] 2024-08-24 15:30
Oh damn
how did I not find it when looking

**Closed** 2024-08-24 16:46 UTC
