### ISSUE TITLE
Dismantling Wave can remove multiple artifacts of one player instead of "up to on"

### ISSUE THREAD

**Issue by Nymra** [Card-Forge/forge#5390] opened 2024-06-07 00:47 UTC
Simple:

I play EDH vs. 3 AI (total players 4)

Dismantling Wave can target 3 of my artifacts/enchantments instead of 0-1 as the rule says.
Dismantling Wave is NOT cycled when this happens.

I noticed similar issues with other cards that target like this but with dismantling wave it happens all the time so I start there...
NOTE: happened with artifacts all the time for me, never with enchantments (at least I do not recall it).

**Comment by tool4ever** [comment] 2024-06-07 06:37
Duplicate of #4242

**Closed by tool4ever** 2024-06-07 06:37 UTC
