### ISSUE TITLE
Casting Lulu, Loyal Hollyphant with Master Chef on the battlefield causes the game to crash

### ISSUE THREAD

**Issue by Cnights** [Card-Forge/forge#2826] opened 2023-04-05 02:00 UTC
**Describe the bug**
In Commander's vs AI when Lulu, Loyal Hollyphant and Master Chef is is your commander the game crashes if Master Chef is on the battlefield and you try to cast Lulu from the command zone. Think it might also crash if cast from hand but not sure. If Lulu is cast first then master chef is cast all seems to work fine. Also haven't tried with other commanders. 

**To Reproduce**
1. Have Lulu, Loyal Hollyphant and Master Chef as your commander.
2. Have Master chef on the battlefield. 
3. Cast Lulu
4. Game crashes

**Expected behavior**
Be adle to cast Lulu with Master chef on the field

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Comment by kevlahnota** [comment] 2023-04-05 04:49
Forge version? Does it crash on 04-05 snapshot?

**Comment by Hanmac** [comment] 2023-04-05 07:41
Duplicate of #2818

**Closed by Hanmac** 2023-04-05 07:41 UTC
