### ISSUE TITLE
Journey to Eternity cant be cast

### ISSUE THREAD

**Issue by Nemesis666first** [Card-Forge/forge#3773] opened 2023-09-14 16:39 UTC
v1.6.58 snap 9.10

When clicking on it, it return in the hand, nothing happen.

**Comment by tool4ever** [comment] 2023-09-14 18:41
where's your screenshot again?

**Comment by Nemesis666first** [comment] 2023-09-14 18:44
There is nothing to show on the screen, no indication or guess of what is happening.

I can pay the mana (I can even pre-tap it to be sure it's not a land issue, which can happen often with Filter Lands), but the spell just return in my hand.

You dont want a screen, you want a video at this point xD .

**Comment by kevlahnota** [comment] 2023-09-14 21:20
> There is nothing to show on the screen, no indication or guess of what is happening.
> 
> I can pay the mana (I can even pre-tap it to be sure it's not a land issue, which can happen often with Filter Lands), but the spell just return in my hand.
> 
> You dont want a screen, you want a video at this point xD .

The point of screenshot is to see any battlefield state if there are cards preventing you to cast the spell since you didn't tell any exact steps to reproduce the issue, what cards are on the field, etc. If you have a video then attach the video here.

**Comment by Nemesis666first** [comment] 2023-09-14 21:25
So you dont want one screenshot, you want as many as opponent there are.

Well, there were no card which prevent to put an Enchantment or an Aura, there were Ascetism on my field, that's all.

**Comment by kevlahnota** [comment] 2023-09-14 21:34
> So you dont want one screenshot, you want as many as opponent there are.
> 
> Well, there were no card which prevent to put an Enchantment or an Aura, there were Ascetism on my field, that's all.

Anything that helps to investigate your issue. You can attach zip file if you want. It's hard to visualize the issue if you don't have clear steps to reproduce it.

**Comment by Nemesis666first** [comment] 2023-09-15 00:25
M1 / P2, nothing on the stack

**Comment by kevlahnota** [comment] 2023-09-15 01:02
> M1 / M2, nothing on the stack
I cannot reproduce the issue on my end, so I'll mark this issue as invalid and close this. Just reopen the issue if you can tell what steps to reproduce the bug and/or attach relevant file (screenshot, gamestate, any extra details to help in debugging). 

https://github.com/Card-Forge/forge/assets/9781539/a47a584f-9070-40e7-9f5f-80896a56e2ae

**Closed by kevlahnota** 2023-09-15 01:02 UTC
Labels: invalid, User Error
