### ISSUE TITLE
Bug with Desert Warfare

### ISSUE THREAD

**Issue by TheLastNarwhal** [Card-Forge/forge#5640] opened 2024-07-18 06:13 UTC
**Describe the bug**
Desert Warfare isn't returning the sacrificed desert to the field at the end of turn. It triggers, but nothing comes back. I assume it's the same with deserts that are sent to the graveyard from your hand or library as well.

**Expected behavior**
For the desert to come back at end of turn.

**Desktop (please complete the following information):**
 - Forge Version: forge-gui-desktop-1.6.64-SNAPSHOT-07-17

**Comment by tool4ever** [comment] 2024-07-18 06:45
Duplicate of #5392

**Closed by tool4ever** 2024-07-18 06:45 UTC
